title: My Awesome Site
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my awesome site.
url: "https://idkac.github.io"
baseurl: "" # the subpath of your site, e.g. /blog

remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-feed
