remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Test
description: >- # this means to ignore newlines until "baseurl:"
  test
url: "https://idkac.github.io"
baseurl: "" # the subpath of your site, e.g. /blog
